### ISSUE TITLE
Worker example does not work

### ISSUE THREAD

**Issue by cquillen2003** [sqlite/sqlite-wasm#39]
The Web Worker example does not work as written in the README.  The browser cannot import this module and it fails without a helpful error message:
```
// In `worker.js`.
import sqlite3InitModule from '@sqlite.org/sqlite-wasm';
```

This import statement is using a bare specifier specific to Node.js and is not compatible with the browser AFAIK.  Is there a browser-compatible build available and an example of using it?

**Comment by tomayac** [comment]
The [demo's `worker.js`](https://github.com/sqlite/sqlite-wasm/blob/54dc60cedace8bb04d13fcf41865fb68461a0412/demo/worker.js#L1) shows how to use this without a bundler. If you have checked out the package locally, run `npm start` and then go to the URL the script tells you.
