### ISSUE TITLE
Issue with SqliteClient

### ISSUE THREAD

**Issue by cquillen2003** [sqlite/sqlite-wasm#41]
I'm having trouble getting the SqliteClient working.  I'm getting an error when calling `sqlite.executeSql()`.  While troubleshooting, I'm finding that the promise returned from the `sqlite.init()` method is not resolving or erroring.  Any help will be greatly appreciated.

**Comment by sgbeal** [comment]
Any information you could provide regarding your browser version, sqlite-wasm version, and error messages would be helpful. Without that, all anyone can do is speculate about the unspecified problem you're having.

**Comment by michaelpeterlee** [comment]
You should not invoke `executeSql()` until `init()` resolves.

I had to find an example outside the documentation to successfully instantiate OPFS web-worker, are happy to share that here; Other SQLite WASM wrappers exist that look more mature, I started here due to being affiliated with SQLite.

**Comment by tomayac** [comment]
> You should not invoke `executeSql()` until `init()` resolves.

Correct. As per the [documentation](https://github.com/sqlite/sqlite-wasm?tab=readme-ov-file#usage-with-the-bundled-sqliteclient-with-opfs-if-available). Please also see the `/demo` folder.

**Comment by tomayac** [comment]
Specifically, the [`comlink.js`](https://github.com/sqlite/sqlite-wasm/blob/main/demo/comlink.js) file.
