### ISSUE TITLE
SqliteClient > Statement escape

### ISSUE THREAD

**Issue by michaelpeterlee** [sqlite/sqlite-wasm#44]
String parsing appears to be happening somewhere, breaking this longstanding cross-platform SQLite statement, below.

![image](https://github.com/sqlite/sqlite-wasm/assets/19398181/79220fc4-afc7-4abe-b111-926a88c6338c)

This statement escapes by presenting double-quotes twice.

```
const sqlite = new SqliteClient(FILENAME, WORKER_PATH);
await sqlite.init();

sqlite.executeSql(
        'CREATE TABLE IF NOT EXISTS queue' +
        '(' +
            'id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
            'object VARCHAR(5000), ' +
        ')'
);

const sql = 'UPDATE queue SET object = REPLACE(REPLACE(object,"processing","queued"),"attempt"":5","attempt"":0")';
sqlite.executeSql(sql);
```

**Comment by tomayac** [comment]
FYI @etiennenoel.

**Comment by sgbeal** [comment]
Note the subtle SQL syntax error in that (copy/pasted verbatim here):

```

sqlite.executeSql(
        'CREATE TABLE IF NOT EXISTS queue' +
        '(' +
            'id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
            'object VARCHAR(5000), ' +
        ')'
);
```

Count the commas.

Tip: i don't know how executeSql() is handling the first argument, but if it's just passing it on to the underlying exec() call then the above can be written more legibly (IMO) with:

```
sqlite.executeSql([
        'CREATE TABLE IF NOT EXISTS queue(',
            'id INTEGER PRIMARY KEY AUTOINCREMENT, ',
            'object VARCHAR(5000), ', // the extra comma is here, btw
        ')'
]);
```

**Comment by michaelpeterlee** [comment]
Thanks and apologies, I hastily condensed that statement for brevity [is more abstract in the actual codebase].

**Comment by michaelpeterlee** [comment]
As a workaround, I refactored to escape the statement differently:

`const sql = 'UPDATE queue SET object = REPLACE(REPLACE(object,\'processing\',\'queued\'),\'attempt":5\',\'attempt":0\')';`

**Comment by tomayac** [comment]
Obsoleted via https://github.com/sqlite/sqlite-wasm/pull/45.
