### ISSUE TITLE
Add SEE to build

### ISSUE THREAD

**Issue by proof-llc** [sqlite/sqlite-wasm#52]
It appears that we can build sqlite/wasm and include SEE (or maybe include a separate branch/tag for it): https://sqlite.org/wasm/doc/trunk/building.md#see

Now that PWAs can efficiently store lots of structured data (thanks to this project), it will be important to have a way to secure some of it.

**Comment by sgbeal** [comment]
The short answer: no.

Details...

Creating the WASM build with SEE support requires an [SEE license](https://www.sqlite.org/purchase/see) and a custom WASM build compiled with _that_ copy of SEE (noting that each SEE build is created for one of several encryption algorithms, so there is no one-size-fits-all build).

Even with SEE support, however, we don't know of any way to keep the password for encrypted databases secret in a JS app. That password has to be _somewhere_ in JS, and how you could securely keep it from being read by a client is a mystery. The only use case which seems feasible is if the users provide, using an app-specific input mechanism, the password every time a db is opened.

**Comment by steida** [comment]
@tomayac Hi, may I have a question? With Chrome, do other applications have access to OPFS content? I'm asking for https://evolu.dev/ whether it would make sense to encrypt Sqlite. Thank you.

**Comment by sgbeal** [comment]
> Our use case is encryption for Electron, where other apps have access to files but don't have access to JS memory. In such a case, SEE makes sense. Am I correct?

As i know nothing at all about Electron apps, i can't say whether it makes sense, i can only tell you that...

1) We know of know way to keep the secrets entirely secret in the JS/WASM environment. The password has to be stored _somewhere_ in that app or prompted from the user, and it can't be _that_ hard to extract it from an Electron app's package format (whatever that is).

2) SEE is commercial, licensed software and it's extremely unlikely that we'll ever be convinced to distribute it in WASM form because every visitor to a page/app hosting it can simply pluck the WASM file from it get their own "free" copy of SEE.

The canonical build process supports creating custom builds, including those with SEE, but we are extremely unlikely to ever publish SEE WASM builds.

> With Chrome, do other applications have access to OPFS content?

No. See <https://stackoverflow.com/questions/77428281/where-does-opfs-with-sqlite-wasm-store-files-for-the-chrome-extension>

**Comment by tomayac** [comment]
Some clarification that I have posted in the [StackOverflow answer](https://stackoverflow.com/a/77578421/6255000), replicated here:

> Note that what I'm going to tell you is an implementation detail of Chrome that could change at any time, but at the time of this writing, this approach works on macOS, the platform you're using according to the screenshots. In the console (not the DevTools console, the actual system console), enter the following command, customizing the `"some unique string you know is in the OPFS file"` part:
> 
> ```bash
> find ~/Library/Application\ Support/Google/Chrome/Default/File\ System -type f -exec grep -q "some unique string you know is in the OPFS file" {} \; -print
> ```
> 
> On macOS, all OPFS files are stored in `~/Library/Application Support/Google/Chrome/Default/File System`, but the problem is locating the file you're interested in, since the file names don't correspond to the file names the developer used in their OPFS code and the folder names don't correspond to the origins. A little `grep` magic and knowledge about the file contents to the rescue…

**Comment by sgbeal** [comment]
More context from [the SEE license docs](https://www.sqlite.org/see/doc/release/www/readme.wiki):

>  You can ship as many copied of the software to your customers as you want so long as you ensure that only compiled binaries are shipped (you cannot distribute source code) and that your customers cannot make additional copies of the software to use for other purposes.

WASM distributions are incompatible with that part of the license because anyone able to load a web page, or download an Electron app, containing such a build can make a copy with ease.

**Comment by steida** [comment]
@sgbeal Thank you for the clarification. That means we can't use SSE.  

@tomayac My question was whether it makes sense to encrypt db, not put secrets inside. The real-world use case, https://github.com/trezor/trezor-suite HW wallet, uses Electron. Private keys are stored safely in HW devices. We need SQLite to store metadata about transactions, and such meta data should stay private as well.

**Comment by proof-llc** [comment]
trezor is a great use case where the secret is stored outside. another use case is to ask the user to input a pin to access secure data (a PWA may have a secure sqlite db and an unencrypted one). if SEE is commercial, perhaps we can consider the following 2 approaches as well:
- [sqlcipher](https://github.com/sqlcipher/sqlcipher) (sqlite extension that adds encryption)
- Filesystem Encryption / Database Encapsulation: allow middleware to package?

**Comment by utelle** [comment]
> if SEE is commercial, perhaps we can consider the following 2 approaches as well:
> 
> * [sqlcipher](https://github.com/sqlcipher/sqlcipher) (sqlite extension that adds encryption)

As far as I know _SQLCipher_ has external dependencies (like [OpenSSL](https://github.com/openssl/openssl) or [libtomcrypt](https://github.com/libtom/libtomcrypt))  for encryption support, and is therefore not well suited in this context.

But maybe [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers) could be an alternative. It has no external dependencies, and is published under a permissive MIT license.
