### ISSUE TITLE
`sqlite3InitModule` fails if global Array prototype has been extended

### ISSUE THREAD

**Issue by grantcox** [sqlite/sqlite-wasm#71]
I am migrating an existing Ember application from `sql.js` to `sqlite-wasm`.  By default, Ember will [extend the global Array prototype](https://guides.emberjs.com/release/configuring-ember/disabling-prototype-extensions/) with some helper functions.

These prototype extensions will be [enumerated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) if an array is iterated over using `for ... in`.  This means "for ... in" does not only iterate over the array elements, it will also iterate over array properties and functions.

The result of this is that the `sqlite3InitModule()` call will fail, with eg:
```
ERROR: 'sqlite3 bootstrap initializer threw:', TypeError: xArg.get(...) is not a function
TypeError: xArg.get(...) is not a function
    at Object.cache.xWrap.convertArgNoCheck (./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:7762:1)
    at Object.sqlite3_vfs_find (./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:7805:1)
    at ./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:10451:1
    at ./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:6782:1
    at Array.forEach (<anonymous>)
    at sqlite3ApiBootstrap (./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:6781:1)
    at ./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:14368:1
    at callRuntimeCallbacks (./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:669:1)
    at postRun (./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:448:1)
    at doRun (./node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:5664:1)
```

Due to this `for ... in` loop:
https://github.com/sqlite/sqlite-wasm/blob/main/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs#L7802-L7804
```
              for (const i in args)
                args[i] = cxw.convertArgNoCheck(argTypes[i], args[i], args, i);
```

Simply replacing this with a `for (let i = 0; i < args.length; i++)` loop fixes the issue.

There are other `for ... in` loops in that file, but as far as I can tell they all iterate over objects not arrays, and handle extended prototypes well.  In any case the above line is all I needed to change to migrate our application from `sql.js` to `sqlite-wasm`. 

I will open a PR for this shortly.

**Comment by grantcox** [comment]
Actually I realize that the source of this issue is in `/ext/wasm/common/whwasmutil.js` of the upstream SQLite WASM extension, and so I have reported this into the SQLite Forum at https://www.sqlite.org/forum/forumpost/b549992634

Feel free to close this if this is the wrong place.

**Comment by sgbeal** [comment]
This has bee addressed in the above-linked forum post.
