### ISSUE TITLE
sqlite3 result code 1: no such vfs: opfs

### ISSUE THREAD

**Issue by bearjaws** [sqlite/sqlite-wasm#81]
Hey all,

I recently migrated my usage of sqlite-wasm from a localhost project to a https hosted domain and it no longer seems to be working. This is using a web worker, Running SQLite3 version 3.46.0

I tried in both Chrome + Firefox and both are broken the same way.

Here is some sample code where I initialize the connection
```javascript
 log('Loading and initializing SQLite3 module...');

    promiser = await new Promise((resolve) => {
      // @ts-expect-error poor TS support from SQLITE3
      const _promiser = sqliteWasm.sqlite3Worker1Promiser({
        onready: () => resolve(_promiser),
      });
    });

    log('Done initializing.');

    const configResponse = await promiser('config-get', {});
    log('Running SQLite3 version', configResponse.result.version.libVersion);
    const openResponse = await promiser('open', {
      filename: 'file:mydb.sqlite3?vfs=opfs',
    });
    dbId = openResponse.dbId;
```

It errors on the openResource promise.

Additionally, I ran this test to see if OPFS was supported:
```
if ('storage' in navigator && 'getDirectory' in navigator.storage) {
  console.log('OPFS is supported');
} else {
  console.log('OPFS is not supported');
}
```
Giving me "OPFS is supported". 

I tried clearing cache but localhost still seems to work, but no other domain does. 

Any help appreciated!

**Comment by sgbeal** [comment]
> I recently migrated my usage of sqlite-wasm from a localhost project to a https hosted domain...

My guess is that you are not emitting the COOP/COEP headers from your remote server. Without those, the OPFS VFS will not be available because it requires the SharedArrayBuffer class (which is only available if the COOP/COEP headers are emitted):

https://sqlite.org/wasm/doc/trunk/persistence.md#coop-coep

> Additionally, I ran this test to see if OPFS was supported:

That particular VFS requires more than OPFS. See the above-linked page for a separate OPFS VFS which does not have the same requirements, but also has other trade-offs.

**Comment by sgbeal** [comment]
Closing ticket, as this is a config-related error, not a library-level bug.

**Comment by solodeveloping** [comment]
To save people some time:

If you are planning to use it inside a **web extension**, **it will not work in Firefox**, see [this StackOverflow issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1674383), the Firefox issues were opened 5 years ago as of now.

In Chromium, folllow [this link](https://developer.chrome.com/docs/extensions/develop/concepts/cross-origin-isolation), it explains how to add the headers in a web extension.

Like this:

```json
{
  "name": "CrossOriginIsolation example",
  "manifest_version": 3,
  "version": "1.1",
  "cross_origin_embedder_policy": {
    "value": "require-corp"
  },
  "cross_origin_opener_policy": {
    "value": "same-origin"
  },
  ...
}
```

If you are using vite in development, set the appropriate headers in the 'server' property of the vite config.

```js
  server: {
    headers: {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
  },
```
