### ISSUE TITLE
Error: Cannot find exported symbol: sqlite3_bind_parameter_name

### ISSUE THREAD

**Issue by cquillen2003** [sqlite/sqlite-wasm#90]
I am getting the following error when running version 3.47.2-build1.

```
sqlite3ApiBootstrap() error: Error: Cannot find exported symbol: sqlite3_bind_parameter_name
    at toss (sqlite3-bundler-friendly.mjs:6254:17)

Exception loading sqlite3 module: TypeError: Cannot set properties of undefined (setting 'scriptInfo')
    at sqlite3-bundler-friendly.mjs:13935:11
    at async initializeSQLite

Initialization error: TypeError Cannot set properties of undefined (setting 'scriptInfo')
```

**Comment by sgbeal** [comment]
> I am getting the following error when running version 3.47.2-build1.

Telling us something about _how_ you get to that point would be helpful.

i cannot reproduce this in the upstream build. `sqlite3_bind_parameter_name()` is showing up both in the Emscripten-generated JS glue and in the wasm file:

```
$ wasm-objdump -x -j export sqlite3.wasm  | grep ter_name
 - func[406] <sqlite3_bind_parameter_name> -> "sqlite3_bind_parameter_name"
 ```

It may be getting lost (stripped out?) somewhere in your deployment process.

**Comment by cquillen2003** [comment]
Closing this issue.  I was using a mismatched version of sqlite2.wasm and sqlite3-opfs-async-proxy.js.
