### ISSUE TITLE
Recommended usage not working

### ISSUE THREAD

**Issue by cquillen2003** [sqlite/sqlite-wasm#91]
The following promise never resolves.  The onready callback is not being called.  

```
const promiser = await new Promise((resolve) => {
    const _promiser = sqlite3Worker1Promiser({
      onready: () => resolve(_promiser),
    });
});
```

I've tried the code in the README and the code in /demo/wrapped-worker.js and the promise does not resolve.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

The onready callback in sqlite3Worker1Promiser was not being called, causing the promise to never resolve. This fix ensures that the onready callback is properly triggered when the worker is ready.

You can review changes in this commit: https://github.com/mark-addams001881/sqlite-sqlite-wasm-91/commit/3bd4016cda5c37c5e57d74e8607930a7dd436340.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sgbeal** [comment]
> You can review changes in this commit: [mark-addams001881@3bd4016](https://github.com/mark-addams001881/sqlite-sqlite-wasm-91/commit/3bd4016cda5c37c5e57d74e8607930a7dd436340).

(Writing as the person who wrote the code being patched...)

The proposed fix is not semantically correct. This part was removed:

```
if (ev && 'sqlite3-api' === ev.type && 'worker1-ready' === ev.result) 
```

Which will make that block fire for any random unknown message ID, which is definitely not the intent. That block is supposed to fire _one_ time immediately after the worker loads and posts its message to the 

As i'm unaware of any other reports of the effect you're seeing, and am unable to reproduce it, i'm currently hesitant to change this code upstream.

If at all possible, please provide a reproducible case.

> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

Thank you for that disclaimer!

**Comment by cquillen2003** [comment]
This is an issue with Safari I think.  Web workers require https, even on localhost it appears.
